// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

/*
Package OpWire is a generated protocol buffer package.

It is generated from these files:
	client.proto

It has these top-level messages:
	Request
	Response
*/
package PaxWire 

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_OpType int32

const (
	Request_READ  Request_OpType = 0
	Request_WRITE Request_OpType = 1
)

var Request_OpType_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}
var Request_OpType_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x Request_OpType) String() string {
	return proto.EnumName(Request_OpType_name, int32(x))
}
func (Request_OpType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ResponseOpResult int32

const (
	Response_WRITESUCCESS ResponseOpResult = 0
	Response_READSUCCESS  ResponseOpResult = 1
	Response_FAILURE      ResponseOpResult = 2
)

var ResponseOpResult_name = map[int32]string{
	0: "WRITESUCCESS",
	1: "READSUCCESS",
	2: "FAILURE",
}
var ResponseOpResult_value = map[string]int32{
	"WRITESUCCESS": 0,
	"READSUCCESS":  1,
	"FAILURE":      2,
}

func (x ResponseOpResult) String() string {
	return proto.EnumName(ResponseOpResult_name, int32(x))
}
func (ResponseOpResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Request struct {
	Type  Request_OpType `protobuf:"varint,1,opt,name=type,enum=OpWire.Request_OpType" json:"type,omitempty"`
	Id    int32          `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Key   string         `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Value string         `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetType() Request_OpType {
	if m != nil {
		return m.Type
	}
	return Request_READ
}

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	Result ResponseOpResult `protobuf:"varint,1,opt,name=result,enum=OpWire.ResponseOpResult" json:"result,omitempty"`
	Read   string           `protobuf:"bytes,2,opt,name=read" json:"read,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetResult() ResponseOpResult {
	if m != nil {
		return m.Result
	}
	return Response_WRITESUCCESS
}

func (m *Response) GetRead() string {
	if m != nil {
		return m.Read
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "OpWire.Request")
	proto.RegisterType((*Response)(nil), "OpWire.Response")
	proto.RegisterEnum("OpWire.Request_OpType", Request_OpType_name, Request_OpType_value)
	proto.RegisterEnum("OpWire.ResponseOpResult", ResponseOpResult_name, ResponseOpResult_value)
}

func init() { proto.RegisterFile("client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbb, 0x69, 0x92, 0x36, 0xd3, 0xd2, 0x6f, 0x19, 0x3e, 0x24, 0x08, 0x42, 0xc8, 0x29,
	0x78, 0xd8, 0x43, 0x3d, 0x7a, 0x2a, 0x35, 0x42, 0x41, 0x28, 0x4c, 0x5a, 0x7a, 0x94, 0x6a, 0xe7,
	0x10, 0x0c, 0xcd, 0x9a, 0x6c, 0x84, 0xfc, 0x07, 0xc1, 0xbf, 0x2c, 0xdd, 0x8d, 0x7a, 0x7b, 0xf7,
	0xdd, 0x87, 0x99, 0x87, 0x81, 0xf9, 0x6b, 0x55, 0xf2, 0xd9, 0x28, 0xdd, 0xd4, 0xa6, 0xc6, 0x70,
	0xab, 0x0f, 0x65, 0xc3, 0xe9, 0xa7, 0x80, 0x09, 0xf1, 0x7b, 0xc7, 0xad, 0xc1, 0x5b, 0xf0, 0x4d,
	0xaf, 0x39, 0x16, 0x89, 0xc8, 0x16, 0xcb, 0x2b, 0xe5, 0x10, 0x35, 0x7c, 0xab, 0xad, 0xde, 0xf5,
	0x9a, 0xc9, 0x32, 0xb8, 0x00, 0xaf, 0x3c, 0xc5, 0x5e, 0x22, 0xb2, 0x80, 0xbc, 0xf2, 0x84, 0x12,
	0xc6, 0x6f, 0xdc, 0xc7, 0xe3, 0x44, 0x64, 0x11, 0x5d, 0x22, 0xfe, 0x87, 0xe0, 0xe3, 0x58, 0x75,
	0x1c, 0xfb, 0xb6, 0x73, 0x8f, 0xf4, 0x06, 0x42, 0x37, 0x07, 0xa7, 0xe0, 0x53, 0xbe, 0x7a, 0x90,
	0x23, 0x8c, 0x20, 0x38, 0xd0, 0x66, 0x97, 0x4b, 0x91, 0x7e, 0x09, 0x98, 0x12, 0xb7, 0xba, 0x3e,
	0xb7, 0x8c, 0x4b, 0x08, 0x1b, 0x6e, 0xbb, 0xca, 0x0c, 0x46, 0xd7, 0x7f, 0x46, 0x8e, 0x50, 0xb5,
	0x7e, 0x76, 0x04, 0x0d, 0x24, 0x22, 0xf8, 0x0d, 0x1f, 0x9d, 0x59, 0x44, 0x36, 0xa7, 0xf7, 0x10,
	0xfd, 0x82, 0x28, 0x61, 0x6e, 0x97, 0x15, 0xfb, 0xf5, 0x3a, 0x2f, 0x0a, 0x39, 0xc2, 0x7f, 0x30,
	0xbb, 0x88, 0xfc, 0x14, 0x02, 0x67, 0x30, 0x79, 0x5c, 0x6d, 0x9e, 0xf6, 0x94, 0x4b, 0xef, 0x25,
	0xb4, 0xf7, 0xba, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x80, 0x10, 0x9f, 0x51, 0x3f, 0x01, 0x00,
	0x00,
}
