FROM ubuntu:xenial

RUN apt update && apt install -y \
	python \
	autoconf \
	automake \
	libtool \
	curl \
	make \
	g++ \
	unzip \
	net-tools \
	iputils-ping \
	iproute2 \
	sudo \
	wget

RUN wget https://github.com/zeromq/libzmq/releases/download/v4.2.3/zeromq-4.2.3.tar.gz -O /root/zeromq-4.2.2.tar.gz && \
        cd /root &&\
	tar -xvzf zeromq-4.2.2.tar.gz; \
	sudo apt-get update && sudo apt-get install -y libtool pkg-config build-essential autoconf automake uuid-dev; \
	cd zeromq-4.2.3; \
	./configure; \
	sudo make install; \
	sudo ldconfig

RUN wget https://github.com/jedisct1/libsodium/releases/download/1.0.16/libsodium-1.0.16.tar.gz -O /root/libsodium-1.0.16.tar.gz && \
	cd /root && \
	tar -xvzf libsodium-1.0.16.tar.gz; \
	cd libsodium-1.0.16; \
	./configure; \
	make && make check; \
	sudo make install

RUN apt install -y git

RUN git clone https://github.com/protocolbuffers/protobuf.git && \
	cd protobuf && \
	git submodule update --init --recursive && \
	./autogen.sh && \
	./configure && \
	make && \
	make check && \
	sudo make install && \
	sudo ldconfig 

ADD . /clients
