// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation struct {
	// Types that are valid to be assigned to OpType:
	//	*Operation_Setup
	//	*Operation_Put
	//	*Operation_Get
	//	*Operation_Quit
	OpType               isOperation_OpType `protobuf_oneof:"op_type"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_bac96330efda78ce, []int{0}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (dst *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(dst, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

type isOperation_OpType interface {
	isOperation_OpType()
}

type Operation_Setup struct {
	Setup *OperationOpSetup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}
type Operation_Put struct {
	Put *OperationOpPut `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}
type Operation_Get struct {
	Get *OperationOpGet `protobuf:"bytes,3,opt,name=get,proto3,oneof"`
}
type Operation_Quit struct {
	Quit *OperationOpQuit `protobuf:"bytes,4,opt,name=quit,proto3,oneof"`
}

func (*Operation_Setup) isOperation_OpType() {}
func (*Operation_Put) isOperation_OpType()   {}
func (*Operation_Get) isOperation_OpType()   {}
func (*Operation_Quit) isOperation_OpType()  {}

func (m *Operation) GetOpType() isOperation_OpType {
	if m != nil {
		return m.OpType
	}
	return nil
}

func (m *Operation) GetSetup() *OperationOpSetup {
	if x, ok := m.GetOpType().(*Operation_Setup); ok {
		return x.Setup
	}
	return nil
}

func (m *Operation) GetPut() *OperationOpPut {
	if x, ok := m.GetOpType().(*Operation_Put); ok {
		return x.Put
	}
	return nil
}

func (m *Operation) GetGet() *OperationOpGet {
	if x, ok := m.GetOpType().(*Operation_Get); ok {
		return x.Get
	}
	return nil
}

func (m *Operation) GetQuit() *OperationOpQuit {
	if x, ok := m.GetOpType().(*Operation_Quit); ok {
		return x.Quit
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Operation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Operation_OneofMarshaler, _Operation_OneofUnmarshaler, _Operation_OneofSizer, []interface{}{
		(*Operation_Setup)(nil),
		(*Operation_Put)(nil),
		(*Operation_Get)(nil),
		(*Operation_Quit)(nil),
	}
}

func _Operation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Operation)
	// op_type
	switch x := m.OpType.(type) {
	case *Operation_Setup:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Setup); err != nil {
			return err
		}
	case *Operation_Put:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case *Operation_Get:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *Operation_Quit:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Quit); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Operation.OpType has unexpected type %T", x)
	}
	return nil
}

func _Operation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Operation)
	switch tag {
	case 1: // op_type.setup
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OperationOpSetup)
		err := b.DecodeMessage(msg)
		m.OpType = &Operation_Setup{msg}
		return true, err
	case 2: // op_type.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OperationOpPut)
		err := b.DecodeMessage(msg)
		m.OpType = &Operation_Put{msg}
		return true, err
	case 3: // op_type.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OperationOpGet)
		err := b.DecodeMessage(msg)
		m.OpType = &Operation_Get{msg}
		return true, err
	case 4: // op_type.quit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OperationOpQuit)
		err := b.DecodeMessage(msg)
		m.OpType = &Operation_Quit{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Operation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Operation)
	// op_type
	switch x := m.OpType.(type) {
	case *Operation_Setup:
		s := proto.Size(x.Setup)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_Put:
		s := proto.Size(x.Put)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_Quit:
		s := proto.Size(x.Quit)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OperationOpSetup struct {
	Endpoints            []string `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationOpSetup) Reset()         { *m = OperationOpSetup{} }
func (m *OperationOpSetup) String() string { return proto.CompactTextString(m) }
func (*OperationOpSetup) ProtoMessage()    {}
func (*OperationOpSetup) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_bac96330efda78ce, []int{0, 0}
}
func (m *OperationOpSetup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOpSetup.Unmarshal(m, b)
}
func (m *OperationOpSetup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOpSetup.Marshal(b, m, deterministic)
}
func (dst *OperationOpSetup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOpSetup.Merge(dst, src)
}
func (m *OperationOpSetup) XXX_Size() int {
	return xxx_messageInfo_OperationOpSetup.Size(m)
}
func (m *OperationOpSetup) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOpSetup.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOpSetup proto.InternalMessageInfo

func (m *OperationOpSetup) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type OperationOpPut struct {
	Key                  uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationOpPut) Reset()         { *m = OperationOpPut{} }
func (m *OperationOpPut) String() string { return proto.CompactTextString(m) }
func (*OperationOpPut) ProtoMessage()    {}
func (*OperationOpPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_bac96330efda78ce, []int{0, 1}
}
func (m *OperationOpPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOpPut.Unmarshal(m, b)
}
func (m *OperationOpPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOpPut.Marshal(b, m, deterministic)
}
func (dst *OperationOpPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOpPut.Merge(dst, src)
}
func (m *OperationOpPut) XXX_Size() int {
	return xxx_messageInfo_OperationOpPut.Size(m)
}
func (m *OperationOpPut) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOpPut.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOpPut proto.InternalMessageInfo

func (m *OperationOpPut) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *OperationOpPut) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type OperationOpGet struct {
	Key                  uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationOpGet) Reset()         { *m = OperationOpGet{} }
func (m *OperationOpGet) String() string { return proto.CompactTextString(m) }
func (*OperationOpGet) ProtoMessage()    {}
func (*OperationOpGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_bac96330efda78ce, []int{0, 2}
}
func (m *OperationOpGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOpGet.Unmarshal(m, b)
}
func (m *OperationOpGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOpGet.Marshal(b, m, deterministic)
}
func (dst *OperationOpGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOpGet.Merge(dst, src)
}
func (m *OperationOpGet) XXX_Size() int {
	return xxx_messageInfo_OperationOpGet.Size(m)
}
func (m *OperationOpGet) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOpGet.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOpGet proto.InternalMessageInfo

func (m *OperationOpGet) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

type OperationOpQuit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationOpQuit) Reset()         { *m = OperationOpQuit{} }
func (m *OperationOpQuit) String() string { return proto.CompactTextString(m) }
func (*OperationOpQuit) ProtoMessage()    {}
func (*OperationOpQuit) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_bac96330efda78ce, []int{0, 3}
}
func (m *OperationOpQuit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOpQuit.Unmarshal(m, b)
}
func (m *OperationOpQuit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOpQuit.Marshal(b, m, deterministic)
}
func (dst *OperationOpQuit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOpQuit.Merge(dst, src)
}
func (m *OperationOpQuit) XXX_Size() int {
	return xxx_messageInfo_OperationOpQuit.Size(m)
}
func (m *OperationOpQuit) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOpQuit.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOpQuit proto.InternalMessageInfo

type Response struct {
	ResponseTime         float64  `protobuf:"fixed64,1,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_bac96330efda78ce, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponseTime() float64 {
	if m != nil {
		return m.ResponseTime
	}
	return 0
}

func (m *Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Operation)(nil), "Operation")
	proto.RegisterType((*OperationOpSetup)(nil), "Operation.op_setup")
	proto.RegisterType((*OperationOpPut)(nil), "Operation.op_put")
	proto.RegisterType((*OperationOpGet)(nil), "Operation.op_get")
	proto.RegisterType((*OperationOpQuit)(nil), "Operation.op_quit")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_bac96330efda78ce) }

var fileDescriptor_message_bac96330efda78ce = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xdb, 0xb5, 0x9b, 0xeb, 0x75, 0x03, 0x8d, 0x3e, 0x94, 0xe0, 0xc3, 0x98, 0x08, 0x05,
	0xa1, 0x88, 0xfe, 0x02, 0x7d, 0xea, 0x9b, 0x10, 0x7c, 0x1f, 0x15, 0x2f, 0x25, 0x68, 0x9b, 0x98,
	0xdc, 0x08, 0xfb, 0x73, 0xfe, 0x36, 0xc9, 0xed, 0xa6, 0x0c, 0xf7, 0x76, 0x72, 0xcf, 0x77, 0x92,
	0x13, 0x2e, 0x2c, 0x7b, 0xf4, 0xbe, 0xed, 0xb0, 0xb6, 0xce, 0x90, 0x59, 0x7f, 0x4f, 0xa0, 0x78,
	0xb6, 0xe8, 0x5a, 0xd2, 0x66, 0x10, 0xb7, 0x30, 0xf5, 0x48, 0xc1, 0x96, 0xe9, 0x2a, 0xad, 0x4e,
	0xef, 0x2f, 0xea, 0x5f, 0xab, 0x36, 0x76, 0xc3, 0x56, 0x93, 0xa8, 0x91, 0x11, 0x37, 0x90, 0xd9,
	0x40, 0xe5, 0x84, 0xd1, 0xf3, 0x43, 0xd4, 0x06, 0x6a, 0x12, 0x15, 0xfd, 0x88, 0x75, 0x48, 0x65,
	0x76, 0x0c, 0xeb, 0x90, 0xb1, 0x0e, 0x49, 0x54, 0x90, 0x7f, 0x06, 0x4d, 0x65, 0xce, 0x9c, 0x38,
	0xe4, 0xa2, 0xd3, 0x24, 0x8a, 0x09, 0x59, 0xc1, 0x7c, 0x5f, 0x46, 0x5c, 0x41, 0x81, 0xc3, 0x9b,
	0x35, 0x7a, 0x20, 0x5f, 0xa6, 0xab, 0xac, 0x2a, 0xd4, 0xdf, 0x40, 0xde, 0xc1, 0x6c, 0xec, 0x22,
	0xce, 0x20, 0x7b, 0xc7, 0x2d, 0x7f, 0x2b, 0x57, 0x51, 0x8a, 0x4b, 0x98, 0x7e, 0xb5, 0x1f, 0x01,
	0xb9, 0xff, 0x42, 0x8d, 0x07, 0x29, 0x39, 0x11, 0xfb, 0xfc, 0x4b, 0xc8, 0x02, 0x4e, 0x76, 0x55,
	0x9e, 0x46, 0x49, 0x5b, 0x8b, 0xeb, 0x47, 0x98, 0x2b, 0xf4, 0xd6, 0x0c, 0x1e, 0xc5, 0x35, 0x2c,
	0xdd, 0x4e, 0x6f, 0x48, 0xf7, 0xc8, 0xe9, 0x54, 0x2d, 0xf6, 0xc3, 0x17, 0xdd, 0x63, 0xbc, 0x18,
	0x9d, 0xe3, 0x67, 0x0b, 0x15, 0xe5, 0xeb, 0x8c, 0x57, 0xf1, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x4d, 0xe0, 0xaf, 0xf7, 0x9b, 0x01, 0x00, 0x00,
}
