# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='operation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0foperation.proto\"\xdc\x01\n\tOperation\x12$\n\x05setup\x18\x01 \x01(\x0b\x32\x13.Operation.op_setupH\x00\x12 \n\x03put\x18\x02 \x01(\x0b\x32\x11.Operation.op_putH\x00\x12 \n\x03get\x18\x03 \x01(\x0b\x32\x11.Operation.op_getH\x00\x1a\x1d\n\x08op_setup\x12\x11\n\tendpoints\x18\x01 \x03(\t\x1a$\n\x06op_put\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x0c\x1a\x15\n\x06op_get\x12\x0b\n\x03key\x18\x01 \x01(\x04\x42\t\n\x07op_typeb\x06proto3')
)




_OPERATION_OP_SETUP = _descriptor.Descriptor(
  name='op_setup',
  full_name='Operation.op_setup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoints', full_name='Operation.op_setup.endpoints', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=168,
)

_OPERATION_OP_PUT = _descriptor.Descriptor(
  name='op_put',
  full_name='Operation.op_put',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Operation.op_put.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Operation.op_put.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=206,
)

_OPERATION_OP_GET = _descriptor.Descriptor(
  name='op_get',
  full_name='Operation.op_get',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Operation.op_get.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=229,
)

_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setup', full_name='Operation.setup', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='put', full_name='Operation.put', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get', full_name='Operation.get', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OPERATION_OP_SETUP, _OPERATION_OP_PUT, _OPERATION_OP_GET, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='op_type', full_name='Operation.op_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=20,
  serialized_end=240,
)

_OPERATION_OP_SETUP.containing_type = _OPERATION
_OPERATION_OP_PUT.containing_type = _OPERATION
_OPERATION_OP_GET.containing_type = _OPERATION
_OPERATION.fields_by_name['setup'].message_type = _OPERATION_OP_SETUP
_OPERATION.fields_by_name['put'].message_type = _OPERATION_OP_PUT
_OPERATION.fields_by_name['get'].message_type = _OPERATION_OP_GET
_OPERATION.oneofs_by_name['op_type'].fields.append(
  _OPERATION.fields_by_name['setup'])
_OPERATION.fields_by_name['setup'].containing_oneof = _OPERATION.oneofs_by_name['op_type']
_OPERATION.oneofs_by_name['op_type'].fields.append(
  _OPERATION.fields_by_name['put'])
_OPERATION.fields_by_name['put'].containing_oneof = _OPERATION.oneofs_by_name['op_type']
_OPERATION.oneofs_by_name['op_type'].fields.append(
  _OPERATION.fields_by_name['get'])
_OPERATION.fields_by_name['get'].containing_oneof = _OPERATION.oneofs_by_name['op_type']
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), dict(

  op_setup = _reflection.GeneratedProtocolMessageType('op_setup', (_message.Message,), dict(
    DESCRIPTOR = _OPERATION_OP_SETUP,
    __module__ = 'operation_pb2'
    # @@protoc_insertion_point(class_scope:Operation.op_setup)
    ))
  ,

  op_put = _reflection.GeneratedProtocolMessageType('op_put', (_message.Message,), dict(
    DESCRIPTOR = _OPERATION_OP_PUT,
    __module__ = 'operation_pb2'
    # @@protoc_insertion_point(class_scope:Operation.op_put)
    ))
  ,

  op_get = _reflection.GeneratedProtocolMessageType('op_get', (_message.Message,), dict(
    DESCRIPTOR = _OPERATION_OP_GET,
    __module__ = 'operation_pb2'
    # @@protoc_insertion_point(class_scope:Operation.op_get)
    ))
  ,
  DESCRIPTOR = _OPERATION,
  __module__ = 'operation_pb2'
  # @@protoc_insertion_point(class_scope:Operation)
  ))
_sym_db.RegisterMessage(Operation)
_sym_db.RegisterMessage(Operation.op_setup)
_sym_db.RegisterMessage(Operation.op_put)
_sym_db.RegisterMessage(Operation.op_get)


# @@protoc_insertion_point(module_scope)
