// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operation.proto

package operation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation struct {
	// Types that are valid to be assigned to OpType:
	//	*Operation_Setup
	//	*Operation_Put
	//	*Operation_Get
	OpType               isOperation_OpType `protobuf_oneof:"op_type"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_operation_f10814b297bfaa4b, []int{0}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (dst *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(dst, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

type isOperation_OpType interface {
	isOperation_OpType()
}

type Operation_Setup struct {
	Setup *OperationOpSetup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}
type Operation_Put struct {
	Put *OperationOpPut `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}
type Operation_Get struct {
	Get *OperationOpGet `protobuf:"bytes,3,opt,name=get,proto3,oneof"`
}

func (*Operation_Setup) isOperation_OpType() {}
func (*Operation_Put) isOperation_OpType()   {}
func (*Operation_Get) isOperation_OpType()   {}

func (m *Operation) GetOpType() isOperation_OpType {
	if m != nil {
		return m.OpType
	}
	return nil
}

func (m *Operation) GetSetup() *OperationOpSetup {
	if x, ok := m.GetOpType().(*Operation_Setup); ok {
		return x.Setup
	}
	return nil
}

func (m *Operation) GetPut() *OperationOpPut {
	if x, ok := m.GetOpType().(*Operation_Put); ok {
		return x.Put
	}
	return nil
}

func (m *Operation) GetGet() *OperationOpGet {
	if x, ok := m.GetOpType().(*Operation_Get); ok {
		return x.Get
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Operation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Operation_OneofMarshaler, _Operation_OneofUnmarshaler, _Operation_OneofSizer, []interface{}{
		(*Operation_Setup)(nil),
		(*Operation_Put)(nil),
		(*Operation_Get)(nil),
	}
}

func _Operation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Operation)
	// op_type
	switch x := m.OpType.(type) {
	case *Operation_Setup:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Setup); err != nil {
			return err
		}
	case *Operation_Put:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case *Operation_Get:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Operation.OpType has unexpected type %T", x)
	}
	return nil
}

func _Operation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Operation)
	switch tag {
	case 1: // op_type.setup
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OperationOpSetup)
		err := b.DecodeMessage(msg)
		m.OpType = &Operation_Setup{msg}
		return true, err
	case 2: // op_type.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OperationOpPut)
		err := b.DecodeMessage(msg)
		m.OpType = &Operation_Put{msg}
		return true, err
	case 3: // op_type.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OperationOpGet)
		err := b.DecodeMessage(msg)
		m.OpType = &Operation_Get{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Operation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Operation)
	// op_type
	switch x := m.OpType.(type) {
	case *Operation_Setup:
		s := proto.Size(x.Setup)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_Put:
		s := proto.Size(x.Put)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OperationOpSetup struct {
	Endpoints            []string `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationOpSetup) Reset()         { *m = OperationOpSetup{} }
func (m *OperationOpSetup) String() string { return proto.CompactTextString(m) }
func (*OperationOpSetup) ProtoMessage()    {}
func (*OperationOpSetup) Descriptor() ([]byte, []int) {
	return fileDescriptor_operation_f10814b297bfaa4b, []int{0, 0}
}
func (m *OperationOpSetup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOpSetup.Unmarshal(m, b)
}
func (m *OperationOpSetup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOpSetup.Marshal(b, m, deterministic)
}
func (dst *OperationOpSetup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOpSetup.Merge(dst, src)
}
func (m *OperationOpSetup) XXX_Size() int {
	return xxx_messageInfo_OperationOpSetup.Size(m)
}
func (m *OperationOpSetup) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOpSetup.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOpSetup proto.InternalMessageInfo

func (m *OperationOpSetup) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type OperationOpPut struct {
	Key                  uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationOpPut) Reset()         { *m = OperationOpPut{} }
func (m *OperationOpPut) String() string { return proto.CompactTextString(m) }
func (*OperationOpPut) ProtoMessage()    {}
func (*OperationOpPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_operation_f10814b297bfaa4b, []int{0, 1}
}
func (m *OperationOpPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOpPut.Unmarshal(m, b)
}
func (m *OperationOpPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOpPut.Marshal(b, m, deterministic)
}
func (dst *OperationOpPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOpPut.Merge(dst, src)
}
func (m *OperationOpPut) XXX_Size() int {
	return xxx_messageInfo_OperationOpPut.Size(m)
}
func (m *OperationOpPut) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOpPut.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOpPut proto.InternalMessageInfo

func (m *OperationOpPut) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *OperationOpPut) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type OperationOpGet struct {
	Key                  uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationOpGet) Reset()         { *m = OperationOpGet{} }
func (m *OperationOpGet) String() string { return proto.CompactTextString(m) }
func (*OperationOpGet) ProtoMessage()    {}
func (*OperationOpGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_operation_f10814b297bfaa4b, []int{0, 2}
}
func (m *OperationOpGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOpGet.Unmarshal(m, b)
}
func (m *OperationOpGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOpGet.Marshal(b, m, deterministic)
}
func (dst *OperationOpGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOpGet.Merge(dst, src)
}
func (m *OperationOpGet) XXX_Size() int {
	return xxx_messageInfo_OperationOpGet.Size(m)
}
func (m *OperationOpGet) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOpGet.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOpGet proto.InternalMessageInfo

func (m *OperationOpGet) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func init() {
	proto.RegisterType((*Operation)(nil), "Operation")
	proto.RegisterType((*OperationOpSetup)(nil), "Operation.op_setup")
	proto.RegisterType((*OperationOpPut)(nil), "Operation.op_put")
	proto.RegisterType((*OperationOpGet)(nil), "Operation.op_get")
}

func init() { proto.RegisterFile("operation.proto", fileDescriptor_operation_f10814b297bfaa4b) }

var fileDescriptor_operation_f10814b297bfaa4b = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x2f, 0x48, 0x2d,
	0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xea, 0x64, 0xe2, 0xe2,
	0xf4, 0x87, 0x89, 0x09, 0x69, 0x73, 0xb1, 0x16, 0xa7, 0x96, 0x94, 0x16, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x1b, 0x09, 0xeb, 0xc1, 0xa5, 0xf4, 0xf2, 0x0b, 0xe2, 0xc1, 0x52, 0x1e, 0x0c, 0x41,
	0x10, 0x35, 0x42, 0xaa, 0x5c, 0xcc, 0x05, 0xa5, 0x25, 0x12, 0x4c, 0x60, 0xa5, 0x82, 0xa8, 0x4a,
	0x0b, 0x4a, 0x4b, 0x3c, 0x18, 0x82, 0x40, 0xf2, 0x20, 0x65, 0xe9, 0xa9, 0x25, 0x12, 0xcc, 0xd8,
	0x94, 0xa5, 0xa7, 0x82, 0x95, 0xa5, 0xa7, 0x96, 0x48, 0x69, 0x70, 0x71, 0xc0, 0xac, 0x10, 0x92,
	0xe1, 0xe2, 0x4c, 0xcd, 0x4b, 0x29, 0xc8, 0xcf, 0xcc, 0x2b, 0x29, 0x96, 0x60, 0x54, 0x60, 0xd6,
	0xe0, 0x0c, 0x42, 0x08, 0x48, 0x19, 0x70, 0xb1, 0x41, 0x6c, 0x10, 0x12, 0xe0, 0x62, 0xce, 0x4e,
	0xad, 0x04, 0x3b, 0x96, 0x25, 0x08, 0xc4, 0x14, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d,
	0x05, 0xbb, 0x8a, 0x27, 0x08, 0xc2, 0x91, 0x92, 0x02, 0xeb, 0x48, 0x4f, 0xc5, 0xa2, 0xc3, 0x89,
	0x93, 0x8b, 0x3d, 0xbf, 0x20, 0xbe, 0xa4, 0xb2, 0x20, 0x35, 0x89, 0x0d, 0x1c, 0x24, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x11, 0x5f, 0xb5, 0x25, 0x01, 0x00, 0x00,
}
