# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='utils/message.proto',
  package='OpWire',
  syntax='proto3',
  serialized_options=_b('\n\025zookeeper_java.OpWire'),
  serialized_pb=_b('\n\x13utils/message.proto\x12\x06OpWire\"\xe8\x01\n\tOperation\x12\'\n\x03put\x18\x01 \x01(\x0b\x32\x18.OpWire.Operation.op_putH\x00\x12\'\n\x03get\x18\x02 \x01(\x0b\x32\x18.OpWire.Operation.op_getH\x00\x12)\n\x04quit\x18\x03 \x01(\x0b\x32\x19.OpWire.Operation.op_quitH\x00\x1a$\n\x06op_put\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x0c\x1a\x15\n\x06op_get\x12\x0b\n\x03key\x18\x01 \x01(\x04\x1a\x16\n\x07op_quit\x12\x0b\n\x03msg\x18\x01 \x01(\tB\t\n\x07op_type\"V\n\x08Response\x12\x15\n\rresponse_time\x18\x01 \x01(\x01\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x01\x12\n\n\x02id\x18\x05 \x01(\rB\x17\n\x15zookeeper_java.OpWireb\x06proto3')
)




_OPERATION_OP_PUT = _descriptor.Descriptor(
  name='op_put',
  full_name='OpWire.Operation.op_put',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='OpWire.Operation.op_put.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='OpWire.Operation.op_put.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=206,
)

_OPERATION_OP_GET = _descriptor.Descriptor(
  name='op_get',
  full_name='OpWire.Operation.op_get',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='OpWire.Operation.op_get.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=229,
)

_OPERATION_OP_QUIT = _descriptor.Descriptor(
  name='op_quit',
  full_name='OpWire.Operation.op_quit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='OpWire.Operation.op_quit.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=253,
)

_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='OpWire.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='put', full_name='OpWire.Operation.put', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get', full_name='OpWire.Operation.get', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quit', full_name='OpWire.Operation.quit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OPERATION_OP_PUT, _OPERATION_OP_GET, _OPERATION_OP_QUIT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='op_type', full_name='OpWire.Operation.op_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=32,
  serialized_end=264,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='OpWire.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_time', full_name='OpWire.Response.response_time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='OpWire.Response.err', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='OpWire.Response.start', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='OpWire.Response.end', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='OpWire.Response.id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=352,
)

_OPERATION_OP_PUT.containing_type = _OPERATION
_OPERATION_OP_GET.containing_type = _OPERATION
_OPERATION_OP_QUIT.containing_type = _OPERATION
_OPERATION.fields_by_name['put'].message_type = _OPERATION_OP_PUT
_OPERATION.fields_by_name['get'].message_type = _OPERATION_OP_GET
_OPERATION.fields_by_name['quit'].message_type = _OPERATION_OP_QUIT
_OPERATION.oneofs_by_name['op_type'].fields.append(
  _OPERATION.fields_by_name['put'])
_OPERATION.fields_by_name['put'].containing_oneof = _OPERATION.oneofs_by_name['op_type']
_OPERATION.oneofs_by_name['op_type'].fields.append(
  _OPERATION.fields_by_name['get'])
_OPERATION.fields_by_name['get'].containing_oneof = _OPERATION.oneofs_by_name['op_type']
_OPERATION.oneofs_by_name['op_type'].fields.append(
  _OPERATION.fields_by_name['quit'])
_OPERATION.fields_by_name['quit'].containing_oneof = _OPERATION.oneofs_by_name['op_type']
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), dict(

  op_put = _reflection.GeneratedProtocolMessageType('op_put', (_message.Message,), dict(
    DESCRIPTOR = _OPERATION_OP_PUT,
    __module__ = 'utils.message_pb2'
    # @@protoc_insertion_point(class_scope:OpWire.Operation.op_put)
    ))
  ,

  op_get = _reflection.GeneratedProtocolMessageType('op_get', (_message.Message,), dict(
    DESCRIPTOR = _OPERATION_OP_GET,
    __module__ = 'utils.message_pb2'
    # @@protoc_insertion_point(class_scope:OpWire.Operation.op_get)
    ))
  ,

  op_quit = _reflection.GeneratedProtocolMessageType('op_quit', (_message.Message,), dict(
    DESCRIPTOR = _OPERATION_OP_QUIT,
    __module__ = 'utils.message_pb2'
    # @@protoc_insertion_point(class_scope:OpWire.Operation.op_quit)
    ))
  ,
  DESCRIPTOR = _OPERATION,
  __module__ = 'utils.message_pb2'
  # @@protoc_insertion_point(class_scope:OpWire.Operation)
  ))
_sym_db.RegisterMessage(Operation)
_sym_db.RegisterMessage(Operation.op_put)
_sym_db.RegisterMessage(Operation.op_get)
_sym_db.RegisterMessage(Operation.op_quit)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'utils.message_pb2'
  # @@protoc_insertion_point(class_scope:OpWire.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
