/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cjen1.reckon.lib;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.channels.*;
import java.nio.file.*;

import com.fasterxml.jackson.core.JsonProcessingException;

import java.io.RandomAccessFile;

import java.io.IOException;

class LibraryTest {

  @Test void run() throws JsonProcessingException, IOException, ClientException {
    RandomAccessFile fin = new RandomAccessFile("in.bin", "r");
    FileChannel in_c = fin.getChannel();
    RandomAccessFile fout = new RandomAccessFile("out.bin", "rw");
    FileChannel out_c = fout.getChannel();

    IO io = new IO(in_c, out_c); 

    Library.Run(io, ()->new TestClient(), "test client", false);

    fin.close();
    fout.close();
  }
}
