FROM bash
FROM openjdk:7

ADD zkconfs /zkconf

RUN cd / ; \
    wget http://apache.mirror.anlx.net/zookeeper/stable/apache-zookeeper-3.5.5.tar.gz; \ 
    tar xvf apache-zookeeper-3.5.5.tar.gz; \
    mv apache-zookeeper-3.5.5  /usr/local/zookeeper; \
    mkdir /usr/local/zookeeper/data; \
    mkdir /usr/local/zookeeper/logs; \
    cp /zkconf/zoo.cfg /usr/local/zookeeper/conf/zoo.cfg; \
    cp /zkconf/java.env /usr/local/zookeeper/conf/java.env; \
    touch /usr/local/zookeeper/data/myid

EXPOSE 2181 
EXPOSE 2888 
EXPOSE 3888
