FROM bash
FROM openjdk:7

ADD zkconfs /zkconf
ARG ZOO_MY_ID
RUN cd / ; \
    wget http://apache.mirror.anlx.net/zookeeper/stable/zookeeper-3.4.12.tar.gz; \ 
    tar xvf zookeeper-3.4.12.tar.gz; \
    mv zookeeper-3.4.12  /usr/local/zookeeper; \
    mkdir /usr/local/zookeeper/data; \
    mkdir /usr/local/zookeeper/logs; \
    cp /zkconf/zoo.cfg /usr/local/zookeeper/conf/zoo.cfg; \
    cp /zkconf/java.env /usr/local/zookeeper/conf/java.env; \
    touch /usr/local/zookeeper/data/myid

EXPOSE 2181 
EXPOSE 2888 
EXPOSE 3888
